module BoggledApp {

  exception UserNotFoundException {
        string reason;
    };

 exception AlreadyLoggedInException{
          string reason;
     };

  exception InsufficientPlayerException{
          string reason;
     };

  interface Callback {
        void message(in string message);
     };

  interface Boggled {
        void login(in string username, in string password) raises (UserNotFoundException, AlreadyLoggedInException);
        void joinWaitingRoom(in string playerName);
        boolean isGameReadyToStart();
        string getWaitingTime(in Callback objRef);
        string getWaitingRoomInfo(in string playerName);
        string getRoundTime(in Callback objRef, in string gameID);
        boolean submitWord(in string gameID, in string playerName, in string word, out boolean isValid, out boolean canForm, out string response);
        string getGameID(in Callback objRef, in string playerName);
        string getLetters(in string gameID);
  };
};