package BoggledApp.BoggledPackage;


/**
* BoggledApp/BoggledPackage/leaderboardsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, May 14, 2024 3:49:42 PM SGT
*/

public final class leaderboardsHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.GameWinner value[] = null;

  public leaderboardsHolder ()
  {
  }

  public leaderboardsHolder (BoggledApp.GameWinner[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.BoggledPackage.leaderboardsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.BoggledPackage.leaderboardsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.BoggledPackage.leaderboardsHelper.type ();
  }

}
