package BoggledApp.BoggledPackage;


/**
* BoggledApp/BoggledPackage/leaderboardsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

abstract public class leaderboardsHelper
{
  private static String  _id = "IDL:BoggledApp/Boggled/leaderboards:1.0";

  public static void insert (org.omg.CORBA.Any a, BoggledApp.GameWinner[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BoggledApp.GameWinner[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = BoggledApp.GameWinnerHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (BoggledApp.BoggledPackage.leaderboardsHelper.id (), "leaderboards", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BoggledApp.GameWinner[] read (org.omg.CORBA.portable.InputStream istream)
  {
    BoggledApp.GameWinner value[] = null;
    int _len0 = istream.read_long ();
    value = new BoggledApp.GameWinner[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = BoggledApp.GameWinnerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BoggledApp.GameWinner[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      BoggledApp.GameWinnerHelper.write (ostream, value[_i0]);
  }

}
