package BoggledApp.BoggledPackage;


/**
* BoggledApp/BoggledPackage/lettersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, May 14, 2024 3:49:42 PM SGT
*/

public final class lettersHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public lettersHolder ()
  {
  }

  public lettersHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.BoggledPackage.lettersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.BoggledPackage.lettersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.BoggledPackage.lettersHelper.type ();
  }

}
