package BoggledApp;


/**
* BoggledApp/Boggled.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Wednesday, June 12, 2024 1:58:47 PM SGT
*/

public interface Boggled extends BoggledOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Boggled
