package BoggledApp;


/**
* BoggledApp/CallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 29, 2024 7:58:30 PM SGT
*/

public interface CallbackOperations 
{
  void message (String message);
} // interface CallbackOperations
