package BoggledApp;


/**
* BoggledApp/CallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, July 2, 2024 11:44:29 PM CST
*/

public interface CallbackOperations 
{
  void message (String message);
} // interface CallbackOperations
