package BoggledApp;


/**
* BoggledApp/Leaderboards.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, July 2, 2024 11:44:29 PM CST
*/

public final class Leaderboards implements org.omg.CORBA.portable.IDLEntity
{
  public String leaderboard[] = null;

  public Leaderboards ()
  {
  } // ctor

  public Leaderboards (String[] _leaderboard)
  {
    leaderboard = _leaderboard;
  } // ctor

} // class Leaderboards
