package BoggledApp;

/**
* BoggledApp/LeaderboardsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 29, 2024 7:58:30 PM SGT
*/

public final class LeaderboardsHolder implements org.omg.CORBA.portable.Streamable
{
  public Leaderboards value = null;

  public LeaderboardsHolder ()
  {
  }

  public LeaderboardsHolder (Leaderboards initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LeaderboardsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LeaderboardsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LeaderboardsHelper.type ();
  }

}
