package BoggledApp;


/**
* BoggledApp/Leaderboards.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 29, 2024 9:33:59 PM CST
*/

public final class Leaderboards implements org.omg.CORBA.portable.IDLEntity
{
  public String leaderboard[] = null;

  public Leaderboards ()
  {
  } // ctor

  public Leaderboards (String[] _leaderboard)
  {
    leaderboard = _leaderboard;
  } // ctor

} // class Leaderboards
