package BoggledApp;

/**
* BoggledApp/NoWinnerExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 29, 2024 7:58:30 PM SGT
*/

public final class NoWinnerExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public NoWinnerException value = null;

  public NoWinnerExceptionHolder ()
  {
  }

  public NoWinnerExceptionHolder (NoWinnerException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NoWinnerExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NoWinnerExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NoWinnerExceptionHelper.type ();
  }

}
