package BoggledApp;


/**
* BoggledApp/BoggledPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 8, 2024 7:34:01 PM SGT
*/

public abstract class BoggledPOA extends org.omg.PortableServer.Servant
 implements BoggledApp.BoggledOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("joinWaitingRoom", new java.lang.Integer (1));
    _methods.put ("isGameReadyToStart", new java.lang.Integer (2));
    _methods.put ("getWaitingTime", new java.lang.Integer (3));
    _methods.put ("getWaitingRoomInfo", new java.lang.Integer (4));
    _methods.put ("getRoundTime", new java.lang.Integer (5));
    _methods.put ("submitWord", new java.lang.Integer (6));
    _methods.put ("getGameID", new java.lang.Integer (7));
    _methods.put ("getLetters", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BoggledApp/Boggled/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           this.login (username, password);
           out = $rh.createReply();
         } catch (BoggledApp.UserNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           BoggledApp.UserNotFoundExceptionHelper.write (out, $ex);
         } catch (BoggledApp.AlreadyLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           BoggledApp.AlreadyLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // BoggledApp/Boggled/joinWaitingRoom
       {
         String playerName = in.read_string ();
         this.joinWaitingRoom (playerName);
         out = $rh.createReply();
         break;
       }

       case 2:  // BoggledApp/Boggled/isGameReadyToStart
       {
         boolean $result = false;
         $result = this.isGameReadyToStart ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // BoggledApp/Boggled/getWaitingTime
       {
         BoggledApp.Callback objRef = BoggledApp.CallbackHelper.read (in);
         String $result = null;
         $result = this.getWaitingTime (objRef);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // BoggledApp/Boggled/getWaitingRoomInfo
       {
         String playerName = in.read_string ();
         String $result = null;
         $result = this.getWaitingRoomInfo (playerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // BoggledApp/Boggled/getRoundTime
       {
         BoggledApp.Callback objRef = BoggledApp.CallbackHelper.read (in);
         String gameID = in.read_string ();
         String $result = null;
         $result = this.getRoundTime (objRef, gameID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // BoggledApp/Boggled/submitWord
       {
         String gameID = in.read_string ();
         String playerName = in.read_string ();
         String word = in.read_string ();
         org.omg.CORBA.BooleanHolder isValid = new org.omg.CORBA.BooleanHolder ();
         org.omg.CORBA.BooleanHolder canForm = new org.omg.CORBA.BooleanHolder ();
         org.omg.CORBA.StringHolder response = new org.omg.CORBA.StringHolder ();
         boolean $result = false;
         $result = this.submitWord (gameID, playerName, word, isValid, canForm, response);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_boolean (isValid.value);
         out.write_boolean (canForm.value);
         out.write_string (response.value);
         break;
       }

       case 7:  // BoggledApp/Boggled/getGameID
       {
         BoggledApp.Callback objRef = BoggledApp.CallbackHelper.read (in);
         String playerName = in.read_string ();
         String $result = null;
         $result = this.getGameID (objRef, playerName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // BoggledApp/Boggled/getLetters
       {
         String gameID = in.read_string ();
         String $result = null;
         $result = this.getLetters (gameID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledApp/Boggled:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Boggled _this() 
  {
    return BoggledHelper.narrow(
    super._this_object());
  }

  public Boggled _this(org.omg.CORBA.ORB orb) 
  {
    return BoggledHelper.narrow(
    super._this_object(orb));
  }


} // class BoggledPOA
