package BoggledApp;


/**
* BoggledApp/Boggled.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 8, 2024 7:34:01 PM SGT
*/

public interface Boggled extends BoggledOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Boggled
