package Client_Java.BoggledApp;


/**
* BoggledApp/CallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 8, 2024 7:34:01 PM SGT
*/

public interface CallbackOperations 
{
  void message (String message);
} // interface CallbackOperations
