# DO NOT EDIT THIS FILE!
#
# Python module BoggledApp__POA generated by omniidl

import omniORB
omniORB.updateModule("BoggledApp__POA")

# ** 1. Stub files contributing to this module
import boggled_idl

# ** 2. Sub-modules

# ** 3. End
