package BoggledApp;


/**
* BoggledApp/Leaderboards.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, March 10, 2025 8:57:42 PM SGT
*/

public final class Leaderboards implements org.omg.CORBA.portable.IDLEntity
{
  public String leaderboard[] = null;

  public Leaderboards ()
  {
  } // ctor

  public Leaderboards (String[] _leaderboard)
  {
    leaderboard = _leaderboard;
  } // ctor

} // class Leaderboards
