package BoggledApp;


/**
* BoggledApp/Callback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CORBA IDL/boggled.idl
* Monday, June 10, 2024 12:30:57 AM CST
*/

public interface Callback extends CallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Callback
