package BoggledApp;


/**
* BoggledApp/Boggled.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 29, 2024 9:33:54 PM CST
*/

public interface Boggled extends BoggledOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Boggled
