package BoggledApp;


/**
* BoggledApp/Boggled.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CORBA IDL/boggled.idl
* Monday, June 10, 2024 11:49:25 PM CST
*/

public interface Boggled extends BoggledOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Boggled
