package BoggledApp;


/**
* BoggledApp/BoggledOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, June 11, 2024 9:59:22 PM SGT
*/

public interface BoggledOperations 
{
  void login (String username, String password) throws UserNotFoundException, AlreadyLoggedInException;
  void joinWaitingRoom (String playerName);
  boolean isGameReadyToStart ();
  String getWaitingTime (Callback objRef);
  String getWaitingRoomInfo (String playerName);
  String getRoundTime (Callback objRef, String gameID);
  boolean submitWord (String gameID, String playerName, String word, org.omg.CORBA.BooleanHolder isValid, org.omg.CORBA.BooleanHolder canForm, org.omg.CORBA.StringHolder response);
  String getGameID (Callback objRef, String playerName);
  String getLetters (String gameID);
  void logout (String username) throws NotLoggedInException;
} // interface BoggledOperations
