package BoggledApp;


/**
* BoggledApp/CallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 29, 2024 1:28:01 PM CST
*/

public interface CallbackOperations 
{
  void message (String message);
} // interface CallbackOperations
