package BoggledApp;


/**
* BoggledApp/Callback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, June 11, 2024 9:59:22 PM SGT
*/

public interface Callback extends CallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Callback
