package BoggledApp;


/**
* BoggledApp/CallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, June 11, 2024 9:59:22 PM SGT
*/

public interface CallbackOperations 
{
  void message (String message);
} // interface CallbackOperations
