package BoggledApp;


/**
* BoggledApp/CallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../CORBA IDL/boggled.idl
* Monday, June 10, 2024 11:49:25 PM CST
*/

public interface CallbackOperations 
{
  void message (String message);
} // interface CallbackOperations
