package BoggledApp;

/**
* BoggledApp/InsufficientPlayerExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, June 11, 2024 9:59:22 PM SGT
*/

public final class InsufficientPlayerExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public InsufficientPlayerException value = null;

  public InsufficientPlayerExceptionHolder ()
  {
  }

  public InsufficientPlayerExceptionHolder (InsufficientPlayerException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = InsufficientPlayerExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    InsufficientPlayerExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return InsufficientPlayerExceptionHelper.type ();
  }

}
