package BoggledApp;


/**
* BoggledApp/NoWinnerException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, July 2, 2024 11:44:27 PM CST
*/

public final class NoWinnerException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NoWinnerException ()
  {
    super(NoWinnerExceptionHelper.id());
  } // ctor

  public NoWinnerException (String _reason)
  {
    super(NoWinnerExceptionHelper.id());
    reason = _reason;
  } // ctor


  public NoWinnerException (String $reason, String _reason)
  {
    super(NoWinnerExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NoWinnerException
