package BoggledApp;


/**
* BoggledApp/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class Account implements org.omg.CORBA.portable.IDLEntity
{
  public String playerID = null;
  public String username = null;
  public String password = null;

  public Account ()
  {
  } // ctor

  public Account (String _playerID, String _username, String _password)
  {
    playerID = _playerID;
    username = _username;
    password = _password;
  } // ctor

} // class Account
