package BoggledApp;

/**
* BoggledApp/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (BoggledApp.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.AccountHelper.type ();
  }

}
