package BoggledApp;


/**
* BoggledApp/BoggledPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public abstract class BoggledPOA extends org.omg.PortableServer.Servant
 implements BoggledApp.BoggledOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
    _methods.put ("reconnect", new java.lang.Integer (2));
    _methods.put ("playGame", new java.lang.Integer (3));
    _methods.put ("getSettings", new java.lang.Integer (4));
    _methods.put ("getGameWinner", new java.lang.Integer (5));
    _methods.put ("getLeaderboards", new java.lang.Integer (6));
    _methods.put ("sendWord", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BoggledApp/Boggled/login
       {
         try {
           BoggledApp.Account player = BoggledApp.AccountHelper.read (in);
           this.login (player);
           out = $rh.createReply();
         } catch (BoggledApp.UserNotFoundException $ex) {
           out = $rh.createExceptionReply ();
           BoggledApp.UserNotFoundExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // BoggledApp/Boggled/logout
       {
         try {
           BoggledApp.Account player = BoggledApp.AccountHelper.read (in);
           this.logout (player);
           out = $rh.createReply();
         } catch (BoggledApp.NotLoggedInException $ex) {
           out = $rh.createExceptionReply ();
           BoggledApp.NotLoggedInExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // BoggledApp/Boggled/reconnect
       {
         BoggledApp.Account player = BoggledApp.AccountHelper.read (in);
         this.reconnect (player);
         out = $rh.createReply();
         break;
       }

       case 3:  // BoggledApp/Boggled/playGame
       {
         try {
           this.playGame ();
           out = $rh.createReply();
         } catch (BoggledApp.InsufficientPlayersException $ex) {
           out = $rh.createExceptionReply ();
           BoggledApp.InsufficientPlayersExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // BoggledApp/Boggled/getSettings
       {
         BoggledApp.Settings $result = null;
         $result = this.getSettings ();
         out = $rh.createReply();
         BoggledApp.SettingsHelper.write (out, $result);
         break;
       }

       case 5:  // BoggledApp/Boggled/getGameWinner
       {
         BoggledApp.GameResult $result = null;
         $result = this.getGameWinner ();
         out = $rh.createReply();
         BoggledApp.GameResultHelper.write (out, $result);
         break;
       }

       case 6:  // BoggledApp/Boggled/getLeaderboards
       {
         BoggledApp.GameResult $result = null;
         $result = this.getLeaderboards ();
         out = $rh.createReply();
         BoggledApp.GameResultHelper.write (out, $result);
         break;
       }

       case 7:  // BoggledApp/Boggled/sendWord
       {
         try {
           String word = in.read_string ();
           this.sendWord (word);
           out = $rh.createReply();
         } catch (BoggledApp.InvalidWordException $ex) {
           out = $rh.createExceptionReply ();
           BoggledApp.InvalidWordExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledApp/Boggled:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Boggled _this() 
  {
    return BoggledHelper.narrow(
    super._this_object());
  }

  public Boggled _this(org.omg.CORBA.ORB orb) 
  {
    return BoggledHelper.narrow(
    super._this_object(orb));
  }


} // class BoggledPOA
