package BoggledApp;


/**
* BoggledApp/BoggledOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, 16 May 2024 15:13:19 o'clock CST
*/

public interface BoggledOperations 
{
  void login (String username, String password) throws BoggledApp.UserNotFoundException, BoggledApp.AlreadyLoggedInException;
  void joinWaitingRoom (String playerName);
  String say (BoggledApp.Callback objRef, String message);
  boolean isGameReadyToStart ();
  String getWaitingTime (BoggledApp.Callback objRef);
  String getWaitingRoomInfo (String playerName);
  boolean submitWord (String word, org.omg.CORBA.BooleanHolder isValid, org.omg.CORBA.BooleanHolder canForm, org.omg.CORBA.StringHolder response);
  String getGameID (BoggledApp.Callback objRef, String playerName);
  String getLetters (String gameID);
} // interface BoggledOperations
