package BoggledApp;


/**
* BoggledApp/BoggledOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public interface BoggledOperations 
{
  void login (BoggledApp.Account player) throws BoggledApp.UserNotFoundException;
  void signup (String username, String password) throws BoggledApp.UserAlreadyExistsException;
  void logout (BoggledApp.Account player) throws BoggledApp.NotLoggedInException;
  String playGame (String username) throws BoggledApp.InsufficientPlayersException;
  void sendWord (String gameID, String word) throws BoggledApp.InvalidWordException;
  boolean isGameOver (String gameID);
  boolean isRoundOver (String gameID);
  BoggledApp.Settings getSettings ();
  BoggledApp.RoundWinner getRoundWinner ();
  BoggledApp.GameWinner getGameWinner ();
  BoggledApp.GameWinner[] getLeaderboards ();

  // optional for tab screen
  BoggledApp.GamePlayer[] getGamePlayers ();
} // interface BoggledOperations
