package BoggledApp;


/**
* BoggledApp/Callback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, 16 May 2024 15:13:19 o'clock CST
*/

public interface Callback extends CallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Callback
