package BoggledApp;


/**
* BoggledApp/GamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class GamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String playerID = null;
  public boolean playerConnected = false;

  public GamePlayer ()
  {
  } // ctor

  public GamePlayer (String _gameID, String _playerID, boolean _playerConnected)
  {
    gameID = _gameID;
    playerID = _playerID;
    playerConnected = _playerConnected;
  } // ctor

} // class GamePlayer
