package BoggledApp;


/**
* BoggledApp/GameRoom.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class GameRoom implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public boolean gameStarted = false;

  public GameRoom ()
  {
  } // ctor

  public GameRoom (String _gameID, boolean _gameStarted)
  {
    gameID = _gameID;
    gameStarted = _gameStarted;
  } // ctor

} // class GameRoom
