package BoggledApp;

/**
* BoggledApp/GameRoomHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class GameRoomHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.GameRoom value = null;

  public GameRoomHolder ()
  {
  }

  public GameRoomHolder (BoggledApp.GameRoom initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.GameRoomHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.GameRoomHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.GameRoomHelper.type ();
  }

}
