package BoggledApp;

/**
* BoggledApp/GameWinnerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class GameWinnerHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.GameWinner value = null;

  public GameWinnerHolder ()
  {
  }

  public GameWinnerHolder (BoggledApp.GameWinner initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.GameWinnerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.GameWinnerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.GameWinnerHelper.type ();
  }

}
