package BoggledApp;

/**
* BoggledApp/GameResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class GameResultHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.GameResult value = null;

  public GameResultHolder ()
  {
  }

  public GameResultHolder (BoggledApp.GameResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.GameResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.GameResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.GameResultHelper.type ();
  }

}
