package BoggledApp;


/**
* BoggledApp/GameWinner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, May 14, 2024 3:49:42 PM SGT
*/

public final class GameWinner implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String playerID = null;
  public int winningScore = (int)0;

  public GameWinner ()
  {
  } // ctor

  public GameWinner (String _gameID, String _playerID, int _winningScore)
  {
    gameID = _gameID;
    playerID = _playerID;
    winningScore = _winningScore;
  } // ctor

} // class GameWinner
