package BoggledApp;


/**
* BoggledApp/GamePlayer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class GamePlayer implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String playerID = null;
  public boolean isConnected = false;

  public GamePlayer ()
  {
  } // ctor

  public GamePlayer (String _gameID, String _playerID, boolean _isConnected)
  {
    gameID = _gameID;
    playerID = _playerID;
    isConnected = _isConnected;
  } // ctor

} // class GamePlayer
