package BoggledApp;


/**
* BoggledApp/GameWinner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class GameWinner implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String playerID = null;
  public int winningScore = (int)0;

  public GameWinner ()
  {
  } // ctor

  public GameWinner (String _gameID, String _playerID, int _winningScore)
  {
    gameID = _gameID;
    playerID = _playerID;
    winningScore = _winningScore;
  } // ctor

} // class GameWinner
