package BoggledApp;


/**
* BoggledApp/GameResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class GameResult implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String playerID = null;
  public int winningScore = (int)0;

  public GameResult ()
  {
  } // ctor

  public GameResult (String _gameID, String _playerID, int _winningScore)
  {
    gameID = _gameID;
    playerID = _playerID;
    winningScore = _winningScore;
  } // ctor

} // class GameResult
