package BoggledApp;

/**
* BoggledApp/InsufficientPlayersExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, 14 May 2024 18:12:23 o'clock CST
*/

public final class InsufficientPlayersExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.InsufficientPlayersException value = null;

  public InsufficientPlayersExceptionHolder ()
  {
  }

  public InsufficientPlayersExceptionHolder (BoggledApp.InsufficientPlayersException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.InsufficientPlayersExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.InsufficientPlayersExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.InsufficientPlayersExceptionHelper.type ();
  }

}
