package BoggledApp;


/**
* BoggledApp/InsufficientPlayerException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, 16 May 2024 15:13:19 o'clock CST
*/

public final class InsufficientPlayerException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InsufficientPlayerException ()
  {
    super(InsufficientPlayerExceptionHelper.id());
  } // ctor

  public InsufficientPlayerException (String _reason)
  {
    super(InsufficientPlayerExceptionHelper.id());
    reason = _reason;
  } // ctor


  public InsufficientPlayerException (String $reason, String _reason)
  {
    super(InsufficientPlayerExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InsufficientPlayerException
