package BoggledApp;


/**
* BoggledApp/InvalidWordException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, 14 May 2024 18:12:23 o'clock CST
*/

public final class InvalidWordException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidWordException ()
  {
    super(InvalidWordExceptionHelper.id());
  } // ctor

  public InvalidWordException (String _reason)
  {
    super(InvalidWordExceptionHelper.id());
    reason = _reason;
  } // ctor


  public InvalidWordException (String $reason, String _reason)
  {
    super(InvalidWordExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidWordException
