package BoggledApp;


/**
* BoggledApp/RoundWinner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Tuesday, May 14, 2024 3:49:42 PM SGT
*/

public final class RoundWinner implements org.omg.CORBA.portable.IDLEntity
{
  public String gameID = null;
  public String playerID = null;
  public int roundScore = (int)0;

  public RoundWinner ()
  {
  } // ctor

  public RoundWinner (String _gameID, String _playerID, int _roundScore)
  {
    gameID = _gameID;
    playerID = _playerID;
    roundScore = _roundScore;
  } // ctor

} // class RoundWinner
