package BoggledApp;

/**
* BoggledApp/SettingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class SettingsHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.Settings value = null;

  public SettingsHolder ()
  {
  }

  public SettingsHolder (BoggledApp.Settings initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.SettingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.SettingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.SettingsHelper.type ();
  }

}
