package BoggledApp;


/**
* BoggledApp/Settings.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Monday, May 6, 2024 8:09:33 PM SGT
*/

public final class Settings implements org.omg.CORBA.portable.IDLEntity
{
  public int waitingTime = (int)0;
  public int roundTime = (int)0;
  public int roundsToWin = (int)0;

  public Settings ()
  {
  } // ctor

  public Settings (int _waitingTime, int _roundTime, int _roundsToWin)
  {
    waitingTime = _waitingTime;
    roundTime = _roundTime;
    roundsToWin = _roundsToWin;
  } // ctor

} // class Settings
