package BoggledApp;

/**
* BoggledApp/UserNotFoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Saturday, June 8, 2024 5:10:09 PM CST
*/

public final class UserNotFoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.UserNotFoundException value = null;

  public UserNotFoundExceptionHolder ()
  {
  }

  public UserNotFoundExceptionHolder (BoggledApp.UserNotFoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.UserNotFoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.UserNotFoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.UserNotFoundExceptionHelper.type ();
  }

}
