package BoggledApp;

/**
* BoggledApp/UserAlreadyExistsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class UserAlreadyExistsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public BoggledApp.UserAlreadyExistsException value = null;

  public UserAlreadyExistsExceptionHolder ()
  {
  }

  public UserAlreadyExistsExceptionHolder (BoggledApp.UserAlreadyExistsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BoggledApp.UserAlreadyExistsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BoggledApp.UserAlreadyExistsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BoggledApp.UserAlreadyExistsExceptionHelper.type ();
  }

}
