package BoggledApp;


/**
* BoggledApp/UserAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from boggled.idl
* Thursday, May 9, 2024 12:20:24 PM CST
*/

public final class UserAlreadyExistsException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public UserAlreadyExistsException ()
  {
    super(UserAlreadyExistsExceptionHelper.id());
  } // ctor

  public UserAlreadyExistsException (String _reason)
  {
    super(UserAlreadyExistsExceptionHelper.id());
    reason = _reason;
  } // ctor


  public UserAlreadyExistsException (String $reason, String _reason)
  {
    super(UserAlreadyExistsExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class UserAlreadyExistsException
